# Generated by Django 4.0.4 on 2022-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='error',
            field=models.CharField(default='', max_length=50),
        ),
    ]
